name: Docker 2 Gz Releaser

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

  pull_request:
    branches: [ main ]
    
concurrency:
  group: workflow-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get current image
      id: image
      run: echo "::set-output name=image::$(cat docker-image.txt)"
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
      
    - name: docker pull image
      run: docker pull ${{ steps.image.outputs.image }}
      
    - name: docker save image
      run: docker save ${{ steps.image.outputs.image }} | gzip > ${{ steps.image.outputs.image }}.gz
    
    - name: get size of file
      run: ls -lah

    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        file: "*.gz"
        overwrite: true
        verbose: true
